spring.application.name=adventureXPBackend

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Configuration
spring.config.activate.on-profile=mysql
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}