# ===========================
# COMMON CONFIG
# ===========================
spring.application.name=adventureXPBackend
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
# H2 PROFILE
# ===========================
#spring.config.activate.on-profile=h2
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ===========================
# LOCAL-MYSQL PROFILE (Local with MySQL Workbench)
# ===========================
spring.config.activate.on-profile=local-mysql
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
##spring.h2.console.enabled=false

# ===========================
# DOCKER-MYSQL PROFILE (Docker Container MySQL)
# ===========================
#spring.config.activate.on-profile=mysql
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=${DB_URL}
#spring.datasource.driver-class-name=${DB_DRIVER}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.h2.console.enabled=false
